### ISSUE TITLE
Displays 100% when it shouldn't.

### ISSUE THREAD

**Issue by doubleangels** [Benhgift/work_time_percent_applet#7]
If the current time is say 5:10pm, and you start the applet using `python3 main.py 17 1`, the applet displays 100%.

**Comment by Benhgift** [comment]
Yep! It's currently broken when trying to do any work-time range that crosses over midnight. I'm trying to think of a good way to solve it. 

It's pretty much due to this line: 

https://github.com/Benhgift/work_time_percent_applet/blob/master/work_percent.py#L17

And the other if statement. Because those both trigger wrong when the time crosses midnight. 

I'm not sure of a good way to fix it though. I thinking maybe make a special `work_percent` function to call instead of that one for the midnight crossing case (when `work_start > work_end`)

**Comment by Benhgift** [comment]
Added a heaping chunk of if statements to fix this, whew! I'm sure there's a prettier way. Any refactoring is very welcome! 

https://github.com/Benhgift/work_time_percent_applet/commit/dfb0b6e39fc95c725da4515532adb4b960c88cf4
